# Generated by Django 2.0.13 on 2019-05-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190512_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdata',
            old_name='description',
            new_name='info',
        ),
    ]
