# Generated by Django 2.0.13 on 2019-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190512_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='array',
        ),
        migrations.RemoveField(
            model_name='bookdata',
            name='ndim',
        ),
        migrations.AddField(
            model_name='bookdata',
            name='keyword',
            field=models.TextField(default='책'),
        ),
    ]
